ALTER TABLE PATIENT DROP CONSTRAINT PATIENT_CLINIC_ID
ALTER TABLE TREATMENT DROP CONSTRAINT TRTMENTphysicianfk
ALTER TABLE TREATMENT DROP CONSTRAINT TRTMENTrdologistfk
ALTER TABLE TREATMENT DROP CONSTRAINT TREATMENTsurgeonfk
ALTER TABLE TREATMENT DROP CONSTRAINT TREATMENTpatientfk
ALTER TABLE PROVIDER DROP CONSTRAINT PROVIDER_clinic_fk
ALTER TABLE RADDATE DROP CONSTRAINT RDDTrdlgytrtmentfk
DROP TABLE CLINIC
DROP TABLE PATIENT
DROP TABLE TREATMENT
DROP TABLE PROVIDER
DROP TABLE RADDATE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
